### PR TITLE
Small changes to GetInstances data source

### PR DESCRIPTION
**Pull request by aarani**

### CODE REVIEW

**Comment by knocte** [comment]
1st commit msg: Add -> add
2nd commit: I don't see the behaviour change

**Comment by aarani** [comment]
> 1st commit msg: Add -> add

Will fix.

> 2nd commit: I don't see the behaviour change

The behaviour is actually changed in the terraform driver this commit just points to the new driver instead of the old one

**Comment by aarani** [comment]
> 1st commit msg: Add -> add 2nd commit: I don't see the behaviour change

Addressed.

**Comment by knocte** [comment]
> The behaviour is actually changed in the terraform driver this commit just points to the new driver instead of the old one

Point to the change in the driver then? (in the commit msg)

**Comment by aarani** [comment]
> > The behaviour is actually changed in the terraform driver this commit just points to the new driver instead of the old one
> 
> Point to the change in the driver then? (in the commit msg)

Done.

**Pull request merged**
